config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  root 'pages#batman_vs_superman'
  get 'pages/batman'
  get 'pages/superman'
  get 'pages/votos'
  get 'pages/batman_vs_superman'
  post 'pages/votos_batman'
  post 'pages/votos_superman'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/votos_batman.rb
class VotosBatman < ApplicationRecord
end

app/models/votos_superman.rb
class VotosSuperman < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1
  end

  def page2
  	render layout: "bootstrap"
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def batman
  end

  def superman
  end

  def batman_vs_superman 
  end

  def votos_batman
  	VotosBatman.create(name: params[:name], email: params[:mail])
  	redirect_to pages_batman_vs_superman_path, notice: "El nombre #{params[:name]} ha sido guardado"
  end

  def votos_superman
  	VotosSuperman.create(name: params[:name], email: params[:mail])
 	redirect_to pages_batman_vs_superman_path, notice: "El nombre #{params[:name]} ha sido guardado"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<img src="<%= asset_path 'superheroes.jpg'%>" class="img-responsive">

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Find me in app/views/experiments/page2.html.erb</p>

app/views/experiments/page3.html.erb
<h1>Experiments#page3</h1>
<p>Find me in app/views/experiments/page3.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body class="<%= params[:controller] %> <%= params[:action] %>">
    <div class="container">
    <%= yield %>  
    </div>
  </body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Experiments</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="<%= params[:controller] %> <%= params[:action] %>">
  <%= render "navbar/navbar" %> 
    <div class="container">
    <%= yield %>  
    </div>
  </body>
</html>

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=experiments_page1_path%>">Index</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%=experiments_page1_path%>">Page1 <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= experiments_page2_path %>">Page2</a></li>
        <li><a href="<%= experiments_page3_path %>">Page3</a></li>
<!--         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
<!--       <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/batman-vs-superman.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
	<a href="<%= pages_batman_path %>"><h2>BATMAN</h2></a>
	<img src="<%= asset_path 'batman2.jpg'%>" class="img-responsive">
	

	<form action="<%= pages_votos_batman_path %>" method="POST" autocomplete="off">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	
		<div><h6>Nombre</h6><input type="text" autofocus="true" required name="name"></div>
		<div><h6>Email</h6><input type="mail" required name="mail"></div>
		<button type="submit">Enviar</button>
		<h2>Votos : <%= VotosBatman.count %></h2>
	</form>
  </div>
  <div class="col-md-6">
	<a href="<%= pages_superman_path %>"><h2>SUPERMAN</h2></a>
	<img src="<%= asset_path 'superman2.jpg'%>" class="img-responsive">

	<form action="<%= pages_votos_superman_path %>" method="POST" autocomplete="off">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		<div><h6>Nombre</h6><input type="text" autofocus="true" required name="name"></div>
		<div><h6>Email</h6><input type="mail" required name="mail"></div>
		<button type="submit">Enviar</button>
		  <h2>Votos : <%= VotosSuperman.count %></h2>
	</form>

  </div>
</div>

app/views/pages/batman.html.erb
<h1>I am Batman</h1>

app/views/pages/batman_vs_superman.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
	<a href="<%= pages_batman_path %>"><h2>BATMAN</h2></a>
	<img src="<%= asset_path 'batman2.jpg'%>" class="img-responsive">
	

	<form action="<%= pages_votos_batman_path %>" method="POST" autocomplete="off">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	
		<div><h6>Nombre</h6><input type="text" autofocus="true" required name="name"></div>
		<div><h6>Email</h6><input type="mail" required name="mail"></div>
		<button type="submit">Enviar</button>
		<h2>Votos : <%= VotosBatman.count %></h2>
	</form>
  </div>
  <div class="col-md-6">
	<a href="<%= pages_superman_path %>"><h2>SUPERMAN</h2></a>
	<img src="<%= asset_path 'superman2.jpg'%>" class="img-responsive">

	<form action="<%= pages_votos_superman_path %>" method="POST" autocomplete="off">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		<div><h6>Nombre</h6><input type="text" autofocus="true" required name="name"></div>
		<div><h6>Email</h6><input type="mail" required name="mail"></div>
		<button type="submit">Enviar</button>
		  <h2>Votos : <%= VotosSuperman.count %></h2>
	</form>

  </div>
</div>

app/views/pages/superman.html.erb
<h1>This looks like a job for Superman</h1>